[package]
name = "bind_test"
version = "0.1.0"
authors = ["pi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[depenencies]

[build-dependencies]
bindgen = "0.53"
